#!/bin/sh
#
# Simple script to change the screen brightness. Requires root rights.
#
# Dependencies:
# - None

path="/sys/class/backlight/intel_backlight"
current="$(cat "$path/brightness")" || exit 1
change=500
max="$(cat "$path/max_brightness")" || 20000

usage() {
    cat << EOF
Usage: chbrightness [OPTION]

OPTIONs:
  show, to show the current brightness
  +,    to increase the brightness by $change
  -,    to decrease the brightness by $change
  N,    where N is a number between 0 and $max
EOF
}

# shellcheck disable=SC2015
case $1 in
    show) echo "$current" ;;
    -) new="$(( current - change ))"
       echo "$(( 0 < new ? new : 0 ))" > $path ;;
    +) new="$(( current + change ))"
       echo "$(( new < max ? max : new ))" > $path ;;
    *) expr "$1" : "^[1-9][0-9]*$" > /dev/null \
           && [ "$1" -le "$max" ] \
           && echo "$1" > $path \
           || usage ;;
esac
