#!/bin/sh
#
# Script to disable the xdg-screensaver

# the hex value of the root window id can be found with
rootwndw="$(xwininfo -root | awk '$1 == "xwininfo:" {print $4}')"
xdg-screensaver suspend "$rootwndw"
