#!/bin/sh

# Script that downloads all files of an audiobook from a website that
# explicitly links to mp3 files in their source code.
#
# IMPORTANT:
# Needs to be executed in an empty directory in order to properly rename all
# the files to something appropriate.
#
# Dependancies:
# - curl
# - wget
# - perl-rename (on arch)

[ $# -ne 1 ] && echo "Usage: dl-audiobook [ audiobooks url ]"

# Global variables
n=0

urls=$(curl -sS "$1" | grep -oP '"https\S*mp3\?_=\d+"')
printf "%s\n" "$urls" | xargs -I {} wget -bq {} 2>/dev/null 

nurls=$(printf "%s" "$urls" | wc -l)
while [ "$(find . -type f | wc -w)" -lt "$nurls" ] && [ "$n" -le 5 ]; do
    n=$(( n + 1 )); sleep 0.3
done

if [ -n "$(ls)" ]; then
    authorTitle=$(echo "$1" | cut -d / -f 4 | sed 's/audiobook//; s/audio-book//')
    perl-rename 's/mp3.*/mp3/' -- *mp3*       # remove the weird file name ending
    perl-rename "s/^/${authorTitle}/" -- *mp3 # add the author name and book title to the file
else
    >&2 echo "Error during downloading" 
fi
