#!/bin/sh

# Dependencies:
# - scrot
# - dmenu
# - dmenu-choose-dir (helper script)
# - dmenu-noyes (helper script)

# TODO:
# - testing
# - clean up script

# Define these variables if they are not set as environment variables
[ -z "${DMENU}" ] && export DMENU='dmenu -i -p'
export DMENU="dmenu -i -p"

# Global variables
# shellcheck disable=SC2016
DEFAULT_NAME="$(date '+%Y-%m-%d-%H%M%S')_scrot"
DEFAULT_DIR="$MY_PICTURES_DIR/shots"
DEFAULT_FULL_PATH="${DEFAULT_DIR}${DEFAULT_NAME}"
[ -d "$DEFAULT_DIR" ] || mkdir -p "$DEFAULT_DIR"
SEARCH_DIRS="${MY_PICTURES_DIR} \
             ${MY_DOCUMENTS_DIR}/mnt \
             ${MY_DESKTOP_DIR} \
             /mnt"

usage() {
    >&2 cat << EOF
Usage: $0
EOF
}

take_scrot() {
    # shellcheck disable=SC2016,SC2086
    scrot "$1" $2 -e 'mv $f $$MY_PICTURES_DIR/shots/' || return 1
    [ "${DEFAULT_FULL_PATH}" = "${full_path}" ] || mv "${DEFAULT_FULL_PATH}" "${full_path}"
    return
}

options='Selection\nFullscreen\nActive Window'
choice=$(echo "$options" | ${DMENU} 'Screenshot options:') || exit 1
filename="$(echo "$DEFAULT_NAME" | ${DMENU} 'Enter file name (no extension):').png" || exit 1
dir="$(dmenu-choose-dir '3' "${SEARCH_DIRS}" "Where to store the picture?")" || exit 1
full_path="${dir}/${filename}" 

# test for existence of $dir/$filename
[ -f "${full_path}" ] && ! dmenu-noyes "${full_path} already exists, overwite it?" && exit 1

case "$choice" in
    'Fullscreen')
        dim=$(xwininfo -root | grep geometry | grep -oP '\d+x\d+')
        w=$(echo "$dim" | cut -d x -f 1)
        h=$(echo "$dim" | cut -d x -f 2)
        take_scrot "${DEFAULT_NAME}" "-a 0,0,$w,$h" ;;
    'Selection')     
        take_scrot "${DEFAULT_NAME}" '-s' ;;
    'Active Window') 
        take_scrot "${DEFAULT_NAME}" '-u' ;;
    *) usage && exit 1 ;;
esac
exit
