#!/bin/sh

# TODO:
#  - Use dmenu to ask for music dir

genre=$(find "$XDG_DOCUMENTS_DIR/music2021/" -type d | ${DMENU} "Which genre to play?" -l 10) || exit 1

find "${genre}" -name '*.mp3' | shuf | xargs -I {} mpv '{}' &
