#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

### Setup my environment
# My custom scripts
disable-xdg-screensaver
fehbg &
#xsetroot -cursor_name left_ptr

# Daemons
redshift -c "$XDG_CONFIG_HOME/redshift.conf" &  # Reduce te blue light emitted by the screen
sxhkd &     # Hot key daemon
wired &     # Notification daemon
pulseaudio --daemonize

# Hardware settings
# Find the name/id of the touchpad with 'xinput list' and 'xinput list-props
# <device-name/id>' for all properties
xinput set-prop 'DELL098F:00 04F3:311C Touchpad' 'libinput Tapping Enabled' 1
xinput set-prop 'DELL098F:00 04F3:311C Touchpad' 'libinput Accel Speed' .5
#amixer sset 'PGA3.1 3 Master' 50%

# start the graphical environment
# See ~/.profile for how arguments are passed to .xinitrc
case $1 in
    a) exec awesome ;;
    x) exec xmonad ;;
    *) dwmblocks &
       exec dwm ;;
esac
