# webgoat
alias webgoat='java -jar ~/Downloads/webgoat-server-8.2.2.jar'

# Quickly change directories
alias ..='cd ..'
alias ...='cd ../..'
alias ru='cd /media/br/ru'
alias .d='cd $HOME/Desktop/'
alias .dl='cd $HOME/Downloads/'
alias .c='cd $HOME/.config/'
alias .b='cd $HOME/.local/bin'

# Edit config files
alias vim="$EDITOR"
alias ,b="$EDITOR $HOME/.config/bash/bashrc"
alias ,ba="$EDITOR $HOME/.config/bash/bash_aliases"
alias ,awm="$EDITOR $HOME/.config/awesome/rc.lua"
alias ,v="$EDITOR $HOME/.config/vim/vimrc"

# system
alias ssn='shutdown now'
alias wifioff='nmcli radio wifi off'
alias wifion='nmcli radio wifi on'

# mount usb, writable by non-root users
#alias mounto='sudo mount -o gid=users,fmask=113,dmask=002'
alias mounto='sudo mount -o uid=1000,fmask=113,dmask=002'
alias mtu='sudo mount -o uid=1000,fmask=113,dmask=002 /dev/sda1 /media/br/'
alias mto='sudo umount /dev/sda1'

# apt
alias a='sudo apt'
alias ati='sudo apt install'
alias atr='sudo apt remove'
alias atu='sudo apt update'
alias atuu='sudo apt update && sudo apt upgrade'
alias atar='sudo apt autoremove'

# pacman and yay
alias pacs='doas pacman -S'
alias pacsyu='doas pacman -Syyu'                 # update only standard pkgs
alias yaysua='yay -Sua --noconfirm'              # update only AUR pkgs (yay)
alias yaysyu='yay -Syu --noconfirm'              # update standard pkgs and AUR pkgs (yay)
alias parsua='paru -Sua --noconfirm'             # update only AUR pkgs (paru)
alias parsyu='paru -Syu --noconfirm'             # update standard pkgs and AUR pkgs (paru)
alias unlock='doas rm /var/lib/pacman/db.lck'    # remove pacman lock
alias cleanup='doas pacman -Rns (pacman -Qtdq)'  # remove orphaned packages

# get fastest mirrors
alias mirror="doas reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="doas reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="doas reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="doas reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|ta    il -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# commands with extra flags
alias mvi='mv -i'
alias cpi='cp -i'
alias ll='exa -al --color=always --group-directories-first' # ls replacement
alias md='mkdir -p'

# xclip copy and paste 
alias xc='xclip -selection c'
alias xv='xclip -selection c -o'
## clear clipboard
alias xcc='xclip -sel clip < /dev/null' 

# Programming
alias pip='pip3'
alias note='~/anaconda3/bin/jupyter-notebook'

# Download an audio file from youtube with youtube-dl
alias yt-dl-audio='youtube-dl -x --audio-format mp3'

# Git
alias ta='git add'
alias taa='git add .'
alias tc='git commit'
alias tcache='git config --global credential.helper cache'
alias tcon='git config --global user.name "Your_Name" && git config --global user.email "Your-Email"'
alias tcl='git clone'
alias ts='git status'
## Managing dotfiles
alias dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias dots='dot status'
alias dota='dot add'
alias dotau='dot add --update'
alias dotc='dot commit -m'
alias dotp='dot push'

# Calculator without welcome
alias bc='bc -q'

# Weather report
alias weather='curl wttr.in/'
alias radar='mpv --loop=inf "https://image.buienradar.nl/2.0/image/animation/RadarMapRainWebMercatorNL?width=256&height=256&renderBackground=True&renderBranding=True&renderText=True"'

# wget move wget-hsts file out of $HOME 
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
